### ISSUE TITLE
Error on iOS mobile devices "please delete this app and reinstall"

### ISSUE THREAD

**Issue by deficook** [notiondog/notion.dog#50]
Hey there, sorry for submitting an issue given you do this for free in your spare time - anyway in case you weren't aware of it: 

it seems that loading the page on an iOS device returns a rather awkward error, it's not clear to me what could cause it, whether it's just Notion messing up for some reason. 

![Crypto Twitter Bots](https://user-images.githubusercontent.com/72689693/113567741-7665f000-960f-11eb-9770-0c5406d1f23d.png)

Cheers

**Comment by markliuyuxiang** [comment]
It's notion message. We're very sorry about that.
